export const metadata = {
    title: 'Assignment-Blog',
    description: 'Generated by Sarwar',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
